version: "3.4"
 
services:
 
  inanzzz_wait_php:
    build:
      context: "./php"
    hostname: "wait-php"
    volumes:
      - "..:/app"
    environment:
      PS1: "\\u@\\h:\\w\\$$ "
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "inanzzz_monitoring_fluent_bit"
        tag: "wait_php"
        mode: "non-blocking"
        max-buffer-size: "2m"
        fluentd-async-connect: "true"
 
  inanzzz_wait_nginx:
    build:
      context: "./nginx"
    hostname: "wait-nginx"
    ports:
      - "1080:80"
    volumes:
      - "..:/app"
    depends_on:
      - "inanzzz_wait_php"
    environment:
      PS1: "\\u@\\h:\\w\\$$ "
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "inanzzz_monitoring_fluent_bit"
        tag: "wait_nginx"
        mode: "non-blocking"
        max-buffer-size: "2m"
        fluentd-async-connect: "true"
